version: "3.0"  
services:
  prometheus:
    image: ubuntu/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - network1
    volumes:
      - /root/prometheus-grafana/:/config
      - rabbitmq-monitoring:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yml"
  grafana:
    image: ubuntu/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - network1
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    networks:
      - network1
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - 8080:8080
    networks:
      - network1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
volumes:
  rabbitmq-monitoring:
    external: true
networks:
  network1:
    name: rabbitmq-monitoring
    external: true
